name: CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      
      - name: Build and generate nuxt
        run: |
              npm ci
              npm run generate
              cd .output/public
              echo '.nuxt' > .nojekyll
              git config --global user.email "githubaction"
              git config --global user.name "github action"
              git init
              git add -A
              git commit -m 'Deploy'
              git push -f https://joshste:${{ secrets.GITHUB_TOKEN }}@github.com/joshste/pdf-ajaib-fe.git master:gh-pages
